// src/types/cte.types.ts

export enum StatusCTe {
  RASCUNHO = 'RASCUNHO',
  VALIDADA = 'VALIDADA',
  ASSINADA = 'ASSINADA',
  PROCESSANDO = 'PROCESSANDO',
  AUTORIZADA = 'AUTORIZADA',
  REJEITADA = 'REJEITADA',
  CANCELADA = 'CANCELADA',
  DENEGADA = 'DENEGADA',
}

export enum ModalCTe {
  RODOVIARIO = 'RODOVIARIO',
  AEREO = 'AEREO',
  AQUAVIARIO = 'AQUAVIARIO',
  FERROVIARIO = 'FERROVIARIO',
  DUTOVIARIO = 'DUTOVIARIO',
  MULTIMODAL = 'MULTIMODAL',
}

export enum TipoServicoCTe {
  NORMAL = 0,
  SUBCONTRATACAO = 1,
  REDESPACHO = 2,
  REDESPACHO_INTERMEDIARIO = 3,
  VINCULADO_MULTIMODAL = 4,
}

export enum TipoCTe {
  NORMAL = 'NORMAL',
  COMPLEMENTO_VALORES = 'COMPLEMENTO_VALORES',
  SUBSTITUICAO = 'SUBSTITUICAO',
}

export enum TomadorServicoCTe {
  REMETENTE = 0,
  EXPEDIDOR = 1,
  RECEBEDOR = 2,
  DESTINATARIO = 3,
  OUTROS = 4,
}

export enum IndicadorIECTe {
  CONTRIBUINTE = '1',
  ISENTO = '2',
  NAO_CONTRIBUINTE = '9',
}

export enum CSTICMSCTe {
  TRIBUTACAO_NORMAL = '00',
  REDUCAO_BC = '20',
  ISENTA = '40',
  NAO_TRIBUTADA = '41',
  DIFERIDA = '51',
  ST = '60',
  OUTROS = '90',
}